### PR TITLE
WIP tagging support for LT hline

### PR DESCRIPTION
**Pull request by davidcarlisle**
Code from https://github.com/latex3/tagging-project/issues/90

The notag test fails @u-fischer what's the best way to guard this for the tagging code, clearly an if csname defined test would work but what's the best idiom here or is there a form we can use that's defined in the kernel and doesn't need guarding.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
@u-fischer @frankmittelbach does this look OK for tagging?

**Comment by u-fischer** [comment]
I would suggest to replace `\int_gdecr:N \g__tbl_row_int` by `\tbl_gdecr_row_count:`. Then you will not use an internal command ...

**Comment by u-fischer** [comment]
Tagging looks ok. I'm not sure if it is needed to delay the definition of the dummies to begindocument. Basically either it has been done before \documentclass or not ....

**Comment by davidcarlisle** [comment]
> Tagging looks ok. I'm not sure if it is needed to delay the definition of the dummies to begindocument. Basically either it has been done before \documentclass or not ....

good point I'll move out

**Pull request merged**
